# Generated by Django 4.0.2 on 2022-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_data',
            name='owner_adress',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
